name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scripts to build documentation
      run: |
        python scripts/generate_html_report.py
        python scripts/generate_attribute_pages.py
        python scripts/generate_csv_from_adoc.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/
        git add data/epd_documentation.csv
        git diff --staged --quiet || git commit -m 'Automated documentation build' && git push
